/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tomfrans.davis' at '12/13/17 3:43 PM' with Gradle 2.14.1
 *
 * @author tomfrans.davis, @date 12/13/17 3:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
